name: CI - Programmatic Compliance

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [20]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Delete package-lock.json
        run: rm package-lock.json

      - name: Setup JS SDK
        run: npm ci

      - name: Build JS SDK
        run: npm run build

      # - name: Test
      #   working-directory: ./packages/js-sdk
      #   run: npm test